dados_treino = {
    'Mensagem_do_usuario': [
        "Por favor, acesse o Youtube",
        "Abra o Youtube",
        "Quero acessar o Youtube",
        "Inicie o Youtube",
        "Crie uma pasta na área de trabalho",
        "Faça uma nova pasta na área de trabalho",
        "Nova pasta na área de trabalho",
        "Abra o Google",
        "Acesse o Google",
        "Quero abrir o Google",
        "Abra o VsCode",
        "Inicie o VsCode",
        "Abrir o Visual Studio Code",
        "Realize uma busca no Google por receitas de bolo de cenoura",
        "Pesquise receitas de bolo de cenoura no Google",
        "Procure receitas de bolo de cenoura no Google",
        "Abra o navegador",
        "Inicie o navegador",
        "Quero abrir o navegador",
        "Feche o navegador",
        "Encerre o navegador",
        "Fechar navegador",
        "Abra o bloco de notas",
        "Inicie o bloco de notas",
        "Abrir o notepad",
        "Salve o arquivo",
        "Grave o arquivo",
        "Salvar arquivo",
        "Mostre a previsão do tempo",
        "Qual a previsão do tempo?",
        "Me diga a previsão do tempo",
        "Que horas são?",
        "Me diga as horas",
        "Qual o horário agora?",
        "Abra o Spotify",
        "Inicie o Spotify",
        "Abrir o Spotify",
        "Toque uma música",
        "Coloque uma música",
        "Quero ouvir música",
        "Aumente o volume",
        "Suba o volume",
        "Volume mais alto",
        "Diminua o volume",
        "Abaixe o volume",
        "Volume mais baixo",
        "Desligue o computador",
        "Desligar computador",
        "Quero desligar o PC",
        "Reinicie o computador",
        "Reiniciar computador",
        "Quero reiniciar o PC",
        "Abra o Word",
        "Inicie o Word",
        "Abrir o Microsoft Word",
        "Abra o Excel",
        "Inicie o Excel",
        "Abrir o Microsoft Excel",
        "Envie um e-mail",
        "Mandar um e-mail",
        "Quero enviar um e-mail",
        "Leia meus e-mails",
        "Ver meus e-mails",
        "Quero ler meus e-mails",
        "Abra o Facebook",
        "Acesse o Facebook",
        "Entrar no Facebook",
        "Abra o Instagram",
        "Acesse o Instagram",
        "Entrar no Instagram",
        "Tire um print da tela",
        "Capture a tela",
        "Fazer um print",
        "Mostre o calendário",
        "Abrir calendário",
        "Quero ver o calendário",
        "Abra a calculadora",
        "Inicie a calculadora",
        "Abrir calculadora",
        "Traduza 'olá' para inglês",
        "Como se fala 'olá' em inglês?",
        "Tradução de 'olá' para inglês",
        "Qual é a capital da França?",
        "Me diga a capital da França",
        "Capital da França",
        "Abra o painel de controle",
        "Abrir painel de controle",
        "Acesse o painel de controle",
        "Abra as configurações do sistema",
        "Abrir configurações do sistema",
        "Acesse as configurações do sistema"
    ],
    'Comando_a_ser_executado': [
        "Acessando o Youtube...",
        "Acessando o Youtube...",
        "Acessando o Youtube...",
        "Acessando o Youtube...",
        "Criando uma pasta na área de trabalho",
        "Criando uma pasta na área de trabalho",
        "Criando uma pasta na área de trabalho",
        "Abrindo o Google",
        "Abrindo o Google",
        "Abrindo o Google",
        "Abrindo VsCode",
        "Abrindo VsCode",
        "Abrindo VsCode",
        "Pesquisando receitas de bolo de cenoura no Google",
        "Pesquisando receitas de bolo de cenoura no Google",
        "Pesquisando receitas de bolo de cenoura no Google",
        "Abrindo o navegador",
        "Abrindo o navegador",
        "Abrindo o navegador",
        "Fechando o navegador",
        "Fechando o navegador",
        "Fechando o navegador",
        "Abrindo o bloco de notas",
        "Abrindo o bloco de notas",
        "Abrindo o bloco de notas",
        "Salvando o arquivo",
        "Salvando o arquivo",
        "Salvando o arquivo",
        "Mostrando a previsão do tempo",
        "Mostrando a previsão do tempo",
        "Mostrando a previsão do tempo",
        "Mostrando as horas atuais",
        "Mostrando as horas atuais",
        "Mostrando as horas atuais",
        "Abrindo o Spotify",
        "Abrindo o Spotify",
        "Abrindo o Spotify",
        "Tocando uma música",
        "Tocando uma música",
        "Tocando uma música",
        "Aumentando o volume",
        "Aumentando o volume",
        "Aumentando o volume",
        "Diminuindo o volume",
        "Diminuindo o volume",
        "Diminuindo o volume",
        "Desligando o computador",
        "Desligando o computador",
        "Desligando o computador",
        "Reiniciando o computador",
        "Reiniciando o computador",
        "Reiniciando o computador",
        "Abrindo o Word",
        "Abrindo o Word",
        "Abrindo o Word",
        "Abrindo o Excel",
        "Abrindo o Excel",
        "Abrindo o Excel",
        "Enviando um e-mail",
        "Enviando um e-mail",
        "Enviando um e-mail",
        "Lendo seus e-mails",
        "Lendo seus e-mails",
        "Lendo seus e-mails",
        "Abrindo o Facebook",
        "Abrindo o Facebook",
        "Abrindo o Facebook",
        "Abrindo o Instagram",
        "Abrindo o Instagram",
        "Abrindo o Instagram",
        "Tirando um print da tela",
        "Tirando um print da tela",
        "Tirando um print da tela",
        "Mostrando o calendário",
        "Mostrando o calendário",
        "Mostrando o calendário",
        "Abrindo a calculadora",
        "Abrindo a calculadora",
        "Abrindo a calculadora",
        "Traduzindo 'olá' para inglês: hello",
        "Traduzindo 'olá' para inglês: hello",
        "Traduzindo 'olá' para inglês: hello",
        "A capital da França é Paris",
        "A capital da França é Paris",
        "A capital da França é Paris",
        "Abrindo o painel de controle",
        "Abrindo o painel de controle",
        "Abrindo o painel de controle",
        "Abrindo as configurações do sistema",
        "Abrindo as configurações do sistema",
        "Abrindo as configurações do sistema"
    ]
}











